ztn_todo:
    resource: "@ztnTodoBundle/Resources/config/routing.yml"
    prefix:   /

ztn_service:
    resource: "@ztnServiceBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@ztnUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /
    
ztn_utilisateur_registration:
    resource: "@ztnUtilisateurBundle/Resources/config/registration.xml"
    prefix:   /

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"
   prefix:   /
 
fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile
 
fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

